# Generated by Django 3.2.13 on 2022-06-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawwards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='pic.png', upload_to='images/'),
        ),
    ]
